export const offerData = [
  {
    id: 0,
    title: 'Cappuccino',
    flavour: 'Chocolate',
    imageUrl: require('../../assets/images/coffee-1.png'),
    price: 2.25,
    offer: '50%',
    size: 'Large',
  },
  {
    id: 1,
    title: 'Iced Coffee',
    flavour: 'Extra shot',
    imageUrl: require('../../assets/images/coffee-5.jpeg'),
    price: 1.96,
    offer: '40%',
    size: 'Medium',
  },
  {
    id: 2,
    title: 'Cappuccino',
    flavour: 'Milk',
    imageUrl: require('../../assets/images/coffee-2.png'),
    price: 3.34,
    offer: '30%',
    size: 'Small',
  },
  {
    id: 3,
    title: 'Mocha',
    flavour: 'Chocolate',
    imageUrl: require('../../assets/images/coffee-3.webp'),
    price: 3.12,
    offer: '25%',
    size: 'Medium',
  },
  {
    id: 4,
    title: 'Macchiato',
    flavour: 'Milk',
    imageUrl: require('../../assets/images/coffee-4.jpg'),
    price: 1.51,
    offer: '20%',
    size: 'Small',
  },
];
